# Generated by Django 5.2.5 on 2025-12-20 16:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('SALARY', 'Salary Account')], max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=10)),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATMMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atm_id', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_capacity', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=15)),
                ('network_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded Performance')], default='ONLINE', max_length=10)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service'), ('LOW_CASH', 'Low Cash'), ('OFFLINE', 'Offline')], default='OPERATIONAL', max_length=15)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['atm_id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ATMCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired'), ('LOST', 'Lost/Stolen')], default='ACTIVE', max_length=10)),
                ('expiry_date', models.DateField()),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='atm.account')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='atm.customer'),
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('FAILED_LOGIN', 'Failed Login Attempt'), ('PIN_CHANGE', 'PIN Change Attempt'), ('SUSPICIOUS_TRANSACTION', 'Suspicious Transaction'), ('CARD_BLOCKED', 'Card Blocked'), ('ATM_TAMPERING', 'ATM Tampering Detected'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('SYSTEM_ERROR', 'System Error')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atm.account')),
                ('atm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atm.atmmachine')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('WITHDRAWAL', 'Cash Withdrawal'), ('DEPOSIT', 'Cash Deposit'), ('TRANSFER', 'Fund Transfer'), ('BALANCE_INQUIRY', 'Balance Inquiry'), ('MINI_STATEMENT', 'Mini Statement'), ('PIN_CHANGE', 'PIN Change'), ('BILL_PAYMENT', 'Bill Payment')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='SUCCESS', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receipt_printed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='atm.account')),
                ('atm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atm.atmmachine')),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='atm.account')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account', 'timestamp'], name='atm_transac_account_40d322_idx'), models.Index(fields=['transaction_type', 'status'], name='atm_transac_transac_2a9905_idx')],
            },
        ),
    ]
